# Generated by Django 4.2.19 on 2025-03-22 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='shared_with',
        ),
    ]
