# Generated by Django 4.2.19 on 2025-03-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_note_grade_level_alter_note_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='show_on_profile',
            field=models.BooleanField(default=False),
        ),
    ]
