# Generated by Django 5.1.7 on 2025-03-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_note_show_on_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
