# Generated by Django 5.1.7 on 2025-03-25 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_note_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='profile_picture',
        ),
    ]
