# Generated by Django 5.1.7 on 2025-03-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_remove_note_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
