# Generated by Django 5.1.7 on 2025-03-29 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_note_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='is_published',
        ),
    ]
