# Generated by Django 5.1.7 on 2025-04-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_remove_note_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='grade_level',
            field=models.CharField(choices=[('first', 'First Grade'), ('second', 'Second Grade'), ('third', 'Third Grade'), ('fourth', 'Fourth Grade'), ('fifth', 'Fifth Grade'), ('sixth', 'Sixth Grade'), ('seventh', 'Seventh Grade'), ('eighth', 'Eighth Grade'), ('ninth', 'Ninth Grade'), ('tenth', 'Tenth Grade'), ('eleventh', 'Eleventh Grade'), ('twelfth', 'Twelfth Grade')], default='first', max_length=50),
        ),
        migrations.AlterField(
            model_name='note',
            name='subject',
            field=models.CharField(choices=[('mathematics', 'Mathematics'), ('science', 'Science'), ('history', 'History'), ('english', 'English'), ('computers', 'Computer Science'), ('arts', 'Arts')], default='mathematics', max_length=50),
        ),
    ]
