# Generated by Django 5.1.7 on 2025-04-02 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_alter_note_grade_level_alter_note_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='is_public',
        ),
    ]
