# Generated by Django 4.2.19 on 2025-03-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subject_category',
            field=models.CharField(blank=True, choices=[('math', 'Mathematics'), ('science', 'Science'), ('history', 'History'), ('english', 'English'), ('computers', 'Computer Science'), ('arts', 'Arts')], max_length=20, null=True),
        ),
    ]
