# Generated by Django 5.1.7 on 2025-03-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='receiver',
            new_name='recipient',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow_request', 'Follow Request'), ('follow_accepted', 'Follow Accepted'), ('follow_rejected', 'Follow Rejected'), ('like', 'Like'), ('dislike', 'Dislike'), ('comment', 'Comment')], max_length=20),
        ),
    ]
