# Generated by Django 5.1.7 on 2025-03-27 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_receiver_notification_recipient_and_more'),
        ('profile_users', '0005_follow_status_alter_follow_follower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='follow_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='profile_users.follow'),
        ),
    ]
