# Generated by Django 5.1.7 on 2025-03-27 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_follow_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='follow_request',
        ),
    ]
