# Generated by Django 5.1.7 on 2025-03-29 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_remove_notification_follow_request'),
        ('profile_users', '0005_follow_status_alter_follow_follower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='follow_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='profile_users.follow'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow_request', 'Follow Request'), ('follow_accepted', 'Follow Accepted'), ('follow_rejected', 'Follow Rejected'), ('like', 'Like'), ('dislike', 'Dislike'), ('comment', 'Comment'), ('publish', 'Publish'), ('reply', 'reply')], max_length=20),
        ),
    ]
