# Generated by Django 5.1.7 on 2025-03-29 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_note_is_published'),
        ('notifications', '0005_notification_follow_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notes.note'),
        ),
    ]
