# Generated by Django 5.1.7 on 2025-03-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow_request', 'Follow Request'), ('follow', 'Follow'), ('follow_accepted', 'Follow Accepted'), ('follow_rejected', 'Follow Rejected'), ('like', 'Like'), ('dislike', 'Dislike'), ('comment', 'Comment'), ('new_note', 'New Note')], max_length=20),
        ),
    ]
