# Generated by Django 5.1.7 on 2025-04-02 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_notification_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
    ]
