# Generated by Django 5.1.7 on 2025-03-25 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
    ]
