# Generated by Django 5.1.7 on 2025-04-01 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_users', '0008_remove_profile_shared_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='public_profile',
        ),
    ]
