# Generated by Django 5.1.7 on 2025-04-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_users', '0009_remove_profile_public_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='public_profile',
            field=models.BooleanField(default=True),
        ),
    ]
