# Generated by Django 5.1.7 on 2025-04-02 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_users', '0010_profile_public_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='public_profile',
        ),
    ]
